### ISSUE TITLE
EndVector() Error message when saving the model

### ISSUE THREAD

**Issue by slehmann123** [jomjol/neural-network-analog-needle-readout#12]
win11
python 3.7.13
neural-network-analog-needle-readout version 11.0.1
Anaconda started as admin:

when running with the data provided in github

Save the model
Save the model to the file with the "h5" file format

the following error message shows up 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_2388\3173433804.py in <module>
      2 
      3 converter = tf.lite.TFLiteConverter.from_keras_model(model)
----> 4 tflite_model = converter.convert()
      5 open(FileName + ".tflite", "wb").write(tflite_model)

~\.conda\envs\ter_versuch\lib\site-packages\tensorflow\lite\python\lite.py in wrapper(self, *args, **kwargs)
    927   def wrapper(self, *args, **kwargs):
    928     # pylint: disable=protected-access
--> 929     return self._convert_and_export_metrics(convert_func, *args, **kwargs)
    930     # pylint: enable=protected-access
    931 

~\.conda\envs\ter_versuch\lib\site-packages\tensorflow\lite\python\lite.py in _convert_and_export_metrics(self, convert_func, *args, **kwargs)
    919     if not self.exclude_conversion_metadata:
    920       model_object = _populate_conversion_metadata(model_object, self._metadata)
--> 921     return flatbuffer_utils.convert_object_to_bytearray(model_object)
    922 
    923 

~\.conda\envs\ter_versuch\lib\site-packages\tensorflow\lite\tools\flatbuffer_utils.py in convert_object_to_bytearray(model_object)
     82   # Initial size of the buffer, which will grow automatically if needed
     83   builder = flatbuffers.Builder(1024)
---> 84   model_offset = model_object.Pack(builder)
     85   builder.Finish(model_offset, file_identifier=_TFLITE_FILE_IDENTIFIER)
     86   model_bytearray = bytes(builder.Output())

~\.conda\envs\ter_versuch\lib\site-packages\tensorflow\lite\python\schema_py_generated.py in Pack(self, builder)
   5949             for i in reversed(range(len(self.operatorCodes))):
   5950                 builder.PrependUOffsetTRelative(operatorCodeslist[i])
-> 5951             operatorCodes = builder.EndVector(len(self.operatorCodes))
   5952         if self.subgraphs is not None:
   5953             subgraphslist = []

TypeError: EndVector() takes 1 positional argument but 2 were given

**Comment by jomjol** [comment]
This is a deep error message out of the keras tensorflow. Unfortunately I cannot support there.
I can only comment, that the code is working in my environment. I know, this does not help, but I don't have enough knowledge to go deeper.

**Comment by slehmann123** [comment]
Thanks for the hint, that it might be an issue with my environment.
After a search in the internet I downgraded to flatbuffers==1.12 ( was 2.0.0) and the error message disappeared. Which version are you using?
