### ISSUE TITLE
Q: Get the position of window handles?

### ISSUE THREAD

**Issue by M0ebiu5** [jomjol/neural-network-analog-needle-readout#3]
Hi,
i am wondering, if it would be possible to use this system to get the position of multiple window handles in a room. They all look identical and there are only 3 positions to identify (closed, open, tilted).

Also the cam could replace a pir and will maybe soon be able to identify the person(s) in the room.
Thanks for the great project!

**Comment by jomjol** [comment]
Hi M0ebiu5,
sorry for anserweing so late, I did not update this for quite some while and did just not recognize the issue.
Yes, this system can be rather easy trained for other image recognition, too. Identifying the status of a window handle should be rather easy to implement.

**Comment by jomjol** [comment]
No further activities.
