### ISSUE TITLE
How effective is this recognition

### ISSUE THREAD

**Issue by Sunyingbin** [jomjol/neural-network-analog-needle-readout#4]
I think this is very interesting, and finally I want to confirm, you just use the picture of the small dial to let the machine learn the reading, right?

**Comment by jomjol** [comment]
Sorry for the late reply, I just did not recognize your issue. Yes, I just use the small dial to train the maschine. The images are even down sampled to 20x32 (digits) or 32x32 (analog) before training.

**Comment by jomjol** [comment]
No further activities.
