### ISSUE TITLE
about model question

### ISSUE THREAD

**Issue by Sunyingbin** [jomjol/neural-network-analog-needle-readout#5]
Excuse me, the last line of the model structure is model.add(Dense(2)), this is because the model represents the number of digits input? For example, 2.2, no point

**Comment by jomjol** [comment]
No, the final two output neurons have another reason:
this is a trick to handle the periodic nature of the output. If I only use one output neuron, going from 0 to 9.9, then this would need to do an non stetic jump from 9.9 to 0.0. 
As the mathematics behind this kind of neural network is of continuous nature, you will always find an input, that will result in a value betwenn 9.9 and 0.0 and therefore you would have a bad regocnition for counters in the 12o'clock position.
To circumvent this, I used the trick of encoding the angle in a sinus and cosinus value. So the one neuron gives you the sinus and the second one the cosinus value. These functions are periodic on 360° and therefore you do not have this uncontinious problem.
The only thing, that you need to do is to calculate back from the sin and cos to the angle, respecitively the value. This can be done by a atan-function.

**Comment by jomjol** [comment]
No further activities.
