### ISSUE TITLE
Use on different kind of samples

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [jomjol/neural-network-analog-needle-readout#6]
Hi,
    Thank you for this great work. 

I want to test the proposed method on the given meters. Do you think this project can work on this kind of meters?

If no then Can I train the model on my dataset? If yes then how I can prepare the dataset? I have about 500 images and I can also increase the dataset size. Any other suggestions for this task？
Thank you for your cooperation. 

![4226](https://user-images.githubusercontent.com/28862708/100568642-b423d680-3306-11eb-9286-6bb25d8a4d15.jpg) 

![4489](https://user-images.githubusercontent.com/28862708/100568629-ab330500-3306-11eb-8c55-c8309686d324.jpg)

**Comment by jomjol** [comment]
Sorry for the late reply. I have not checked this issues for quite some time. This counter will work in principle, but you most probobly will need to train it, because currently there are not black pointers in the training. 
Let me know, if you are still interested.
