### ISSUE TITLE
Zenner ETKD needle

### ISSUE THREAD

**Issue by AlexpFr** [jomjol/neural-network-analog-needle-readout#7]
I have a Zenner ETKD with a needle like this, is it present in the dataset?
![image](https://user-images.githubusercontent.com/62973006/114412310-42f60900-9bad-11eb-8b49-ab587d47d6be.png)
If not I will try to send you pictures when I have installed the ESP.

**Comment by jomjol** [comment]
I don't know, what is the source of the numbers - just compare some of your digits with images in the training data: https://github.com/jomjol/neural-network-digital-counter-readout/tree/master/ziffer_sortiert_raw
